// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtF5erMELjAwPKXztqFZTtuj_oGQmxP8I',
    appId: '1:966703401686:android:f51e5da522119583b5d777',
    messagingSenderId: '966703401686',
    projectId: 'art-platform-a2f95',
    storageBucket: 'art-platform-a2f95.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH9hggL6KsnhfdRCoTJobMb4UwEprLzW0',
    appId: '1:966703401686:ios:c1915fa7a04d748fb5d777',
    messagingSenderId: '966703401686',
    projectId: 'art-platform-a2f95',
    storageBucket: 'art-platform-a2f95.firebasestorage.app',
    androidClientId: '966703401686-7dn9ebivridjps6ohk38sc3jfqrvl43h.apps.googleusercontent.com',
    iosClientId: '966703401686-vo3p7hhm642omhiqmsegnksphlp5rkpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.artPlatform',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARAB63F0dEJ_5DlbQes0XKJkZ4EdmSVuU',
    appId: '1:966703401686:web:87cbdb1094e8a4e9b5d777',
    messagingSenderId: '966703401686',
    projectId: 'art-platform-a2f95',
    authDomain: 'art-platform-a2f95.firebaseapp.com',
    storageBucket: 'art-platform-a2f95.firebasestorage.app',
    measurementId: 'G-1E4RTR6HBR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH9hggL6KsnhfdRCoTJobMb4UwEprLzW0',
    appId: '1:966703401686:ios:c1915fa7a04d748fb5d777',
    messagingSenderId: '966703401686',
    projectId: 'art-platform-a2f95',
    storageBucket: 'art-platform-a2f95.firebasestorage.app',
    androidClientId: '966703401686-7dn9ebivridjps6ohk38sc3jfqrvl43h.apps.googleusercontent.com',
    iosClientId: '966703401686-vo3p7hhm642omhiqmsegnksphlp5rkpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.artPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARAB63F0dEJ_5DlbQes0XKJkZ4EdmSVuU',
    appId: '1:966703401686:web:a4c9b7fb04ded5c7b5d777',
    messagingSenderId: '966703401686',
    projectId: 'art-platform-a2f95',
    authDomain: 'art-platform-a2f95.firebaseapp.com',
    storageBucket: 'art-platform-a2f95.firebasestorage.app',
    measurementId: 'G-FRYQENX7NG',
  );
}
